MAX_FIELDS = 3
MAX_SUBCATS = 20
MAX_FIELDS_LENGTH = 8
MAX_SUBCAT_LENGTH = 8
MAX_MAINCAT_LENGTH = 12
MAX_TEXT_LENGTH = 100
MAX_DAY_RANGE = 9999
MIN_DAY_RANGE = 1
MAX_INPUT_VALUE = 1000000

MAX_PHONE_LENGTH = 10
MAX_PASSWORD_LENGTH = 25

INVOICE_FETCH_START_DAYS_AGO = 1
INVOICE_FETCH_END_DAYS_AGO = 1