"""CustomTimeV3

Revision ID: 3cc773becd2b
Revises: 669100e60e67
Create Date: 2026-04-06 23:12:27.039607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc773becd2b'
down_revision: Union[str, Sequence[str], None] = '669100e60e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_categories', sa.Column('current_range', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_categories', 'current_range')
    # ### end Alembic commands ###
