"""Gmail_category

Revision ID: 4734b0dd221b
Revises: 02f8c0261ace
Create Date: 2026-05-02 00:49:46.269087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4734b0dd221b'
down_revision: Union[str, Sequence[str], None] = '02f8c0261ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorized_emails',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=False),
    sa.Column('gmail_link', sa.String(), nullable=False),
    sa.Column('received_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['email_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('email_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('email_contacts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_contacts_pkey'))
    )
    op.drop_table('categorized_emails')
    op.drop_table('email_categories')
    # ### end Alembic commands ###
