"""CustomTimeV2

Revision ID: 669100e60e67
Revises: ce806bba0263
Create Date: 2026-04-05 18:39:49.500086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669100e60e67'
down_revision: Union[str, Sequence[str], None] = 'ce806bba0263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_categories', sa.Column('range_options', sa.JSON(), nullable=True))
    op.drop_column('tracker_categories', 'default_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_categories', sa.Column('default_range', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tracker_categories', 'range_options')
    # ### end Alembic commands ###
