"""LifeTracker_V3

Revision ID: 6d6bf51db7e4
Revises: 7bb06f98bce7
Create Date: 2026-03-20 02:25:20.267612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6bf51db7e4'
down_revision: Union[str, Sequence[str], None] = '7bb06f98bce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
