"""CustomTime

Revision ID: 6e99c9e5dd2d
Revises: bf60695e7f5b
Create Date: 2026-04-05 17:58:23.486886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e99c9e5dd2d'
down_revision: Union[str, Sequence[str], None] = 'bf60695e7f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_categories', sa.Column('default_range', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_categories', 'default_range')
    # ### end Alembic commands ###
