"""LifeTracker_V2

Revision ID: 7bb06f98bce7
Revises: 8f51fc731b96
Create Date: 2026-03-20 02:22:12.255060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb06f98bce7'
down_revision: Union[str, Sequence[str], None] = '8f51fc731b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_records', sa.Column('subcat_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('life_records', 'subcat_name')
    # ### end Alembic commands ###
