"""remove_priority_from_calendar

Revision ID: 8d4fbd102b78
Revises: fe3f26b43b98
Create Date: 2026-05-10 20:59:40.430759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4fbd102b78'
down_revision: Union[str, Sequence[str], None] = 'fe3f26b43b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
