"""LifeTracker

Revision ID: 8f51fc731b96
Revises: ec72a480a8cb
Create Date: 2026-03-19 23:49:22.986927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f51fc731b96'
down_revision: Union[str, Sequence[str], None] = 'ec72a480a8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracker_subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tracker_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tracker_categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['tracker_subcategories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('booking_schedules')
    op.drop_table('thsr_profiles')
    op.drop_table('tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pnr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('train_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('train_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departure', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arrival', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_station', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_station', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seats', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('tickets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_pkey'))
    )
    op.create_table('thsr_profiles',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('personal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tgo_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('thsr_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('thsr_profiles_pkey'))
    )
    op.create_table('booking_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('train_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_station', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_station', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('train_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('seat_prefer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trigger_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('booking_schedules_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_schedules_pkey'))
    )
    op.drop_table('life_records')
    op.drop_table('tracker_subcategories')
    op.drop_table('tracker_categories')
    # ### end Alembic commands ###
