"""WeeklyReport

Revision ID: bf60695e7f5b
Revises: ecdecafe5eb4
Create Date: 2026-04-05 17:38:31.998297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf60695e7f5b'
down_revision: Union[str, Sequence[str], None] = 'ecdecafe5eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_categories', sa.Column('last_ai_analysis', sa.Text(), nullable=True))
    op.add_column('tracker_categories', sa.Column('analysis_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_categories', 'analysis_updated_at')
    op.drop_column('tracker_categories', 'last_ai_analysis')
    # ### end Alembic commands ###
