"""initial tables

Revision ID: ec72a480a8cb
Revises: 
Create Date: 2026-03-05 20:04:22.892744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec72a480a8cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dashboard_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('login_notify_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('calendar_notify_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('gpt_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('discord_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('booking_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('train_code', sa.String(), nullable=False),
    sa.Column('start_station', sa.String(), nullable=False),
    sa.Column('end_station', sa.String(), nullable=False),
    sa.Column('train_date', sa.String(), nullable=False),
    sa.Column('seat_prefer', sa.String(), nullable=True),
    sa.Column('first_executed_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_configs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('email_password', sa.String(), nullable=False),
    sa.Column('last_email_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('email_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thsr_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('personal_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tgo_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('pnr', sa.String(), nullable=True),
    sa.Column('train_date', sa.String(), nullable=True),
    sa.Column('train_code', sa.String(), nullable=True),
    sa.Column('departure', sa.String(), nullable=True),
    sa.Column('arrival', sa.String(), nullable=True),
    sa.Column('start_station', sa.String(), nullable=True),
    sa.Column('end_station', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('seats', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('thsr_profiles')
    op.drop_table('email_contacts')
    op.drop_table('email_configs')
    op.drop_table('calendar_events')
    op.drop_table('booking_schedules')
    op.drop_table('users')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
