"""Einvoice_datetocatch

Revision ID: fe3f26b43b98
Revises: e8963cff7919
Create Date: 2026-05-09 22:07:55.694358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3f26b43b98'
down_revision: Union[str, Sequence[str], None] = 'e8963cff7919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stock_watch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('target_up', sa.Float(), nullable=True),
    sa.Column('target_down', sa.Float(), nullable=True),
    sa.Column('last_notified_price', sa.Float(), nullable=True),
    sa.Column('last_close_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('einvoice_configs', sa.Column('last_fetch_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('einvoice_configs', 'last_fetch_date')
    op.drop_table('user_stock_watch')
    # ### end Alembic commands ###
